### ISSUE TITLE
Handle non-editable document files better

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/ClearlyEditable#9]
Need to handle files that aren't editable documents better.

The following is from opening UWP project file :(

```
Clearly Editable - Could not find file 'C:\Users\matt\source\repos\RxtXfDevTest\RxtXfDevTest\RxtXfDevTest.UWP\RxtXfDevTest.UWP.csproj;aca4ca7d-e28d-419e-929c-0df9627acd26'.
Clearly Editable - mscorlib
Clearly Editable -    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at ClearlyEditable.MyRunningDocTableEvents.RefreshWindow(UInt32 docCookie)
```

**Comment by mrlacey** [comment]
addressed in v 2.1
